apiVersion: v1
kind: Pod
metadata:
  name: termination-demo
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    terminationMessagePath: "/tmp/my-log"
    terminationMessagePolicy: FallbackToLogsOnError
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo-user
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo-password
